# Generated by Django 2.1.7 on 2019-04-02 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenter',
            fields=[
                ('agentid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='代理名')),
                ('acode', models.CharField(max_length=20, verbose_name='代理编码')),
                ('cellphone', models.CharField(max_length=11, verbose_name='手机号')),
                ('password', models.CharField(max_length=40, verbose_name='密码')),
                ('gold', models.IntegerField(verbose_name='金币')),
                ('diamond', models.IntegerField(verbose_name='钻石')),
                ('createtime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Agenter',
            },
        ),
        migrations.CreateModel(
            name='LoginRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('logintime', models.DateTimeField(auto_now=True)),
                ('ipaddr', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'LoginRecord',
            },
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('msg', models.TextField()),
                ('pubtime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Mail',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('msg', models.CharField(max_length=300)),
                ('pubtime', models.DateTimeField()),
            ],
            options={
                'db_table': 'Notice',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, verbose_name='用户名')),
                ('nickname', models.CharField(max_length=30, verbose_name='昵称')),
                ('avatoridx', models.IntegerField(verbose_name='头像id')),
                ('gender', models.IntegerField(choices=[('男', 1), ('女', 0)], verbose_name='性别')),
                ('cellphone', models.CharField(max_length=11, verbose_name='手机号')),
                ('password', models.CharField(max_length=41, verbose_name='密码')),
                ('gold', models.IntegerField(verbose_name='金币')),
                ('diamond', models.IntegerField(verbose_name='钻石')),
                ('createtime', models.DateTimeField(auto_now=True)),
                ('promotecode', models.CharField(max_length=10, verbose_name='推广码')),
                ('referrer', models.CharField(max_length=10, verbose_name='推荐人')),
                ('accountdisable', models.BooleanField(default=False, verbose_name='账号是否被封')),
                ('isrobot', models.BooleanField(default=False, verbose_name='是否为机器人')),
                ('agentid', models.ForeignKey(blank=True, db_column='agentid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.Agenter')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.AddField(
            model_name='loginrecord',
            name='userid',
            field=models.ForeignKey(blank=True, db_column='userid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.User'),
        ),
    ]
